In [ ]:
import numpy as np

Introducing Numpy Array

\documentclass[tikz,border=2mm]{standalone} 
\usetikzlibrary{positioning,matrix, arrows.meta}

\begin{document}
\begin{tikzpicture}
\matrix (A) [matrix of nodes, nodes={draw, minimum size=8mm},
    column sep=-\pgflinewidth]{
    3 & 4 & 2 & 1 & 4 & 1 & 2 & 3\\};
\foreach \i [evaluate=\i as \ni using {int(\i)},
                evaluate=\i as \ntext using {int(\i-1)}] in {1,3,4,6} 
    \draw [{Stealth}-, red!70] (A-1-\ni.south west)--++(-90:5mm) node[below] {\ntext};
\end{tikzpicture}
\end{document}

Simple creation of array

In [ ]:
a=np.array([0,1,2,3])

In [ ]:
print(a)

[0 1 2 3]


In [ ]:
a

array([0, 1, 2, 3])

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


Checking the type

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
arr.ndim

2

In [ ]:
type(a)

numpy.ndarray

In [ ]:
a.dtype

dtype('int64')

Dimension 

In [ ]:
a.ndim

1

Array shape

In [ ]:
a.shape

(4,)

Array Operation

In [ ]:
a=np.array([1,2,3,4])
b=np.array([2,3,4,5])

In [ ]:
a+b

array([3, 5, 7, 9])

In [ ]:
a*b

array([ 2,  6, 12, 20])

In [ ]:
a**b

array([   1,    8,   81, 1024])

Math functions

In [ ]:
#Example create array fron 0.0 to 10.0
x=np.arange(11.)

In [ ]:
x

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
#multiply via scalar quantitity c=0.62
c=0.62
c*x

array([0.  , 0.62, 1.24, 1.86, 2.48, 3.1 , 3.72, 4.34, 4.96, 5.58, 6.2 ])

In [ ]:
#applying a math function to array
y=np.sin(x)

Indexing of array element in Numpy

In [ ]:
a[0]

1

In [ ]:
a[0]=10

In [ ]:
a

array([10,  2,  3,  4])

Remeber the type of array

In [ ]:
#if trying to assign float (decimal value to int array)
a[0]=12.2
a

array([12,  2,  3,  4])

In [ ]:
a.fill(-3.1)
a

array([-3, -3, -3, -3])

Multi dimensional Array

In [ ]:
a=np.array([[0,1,2,3],
            [10,11,12,13]])

In [ ]:
a

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13]])

In [ ]:
a.shape

(2, 4)

In [ ]:
a.size

8

In [ ]:
a.ndim

2

In [ ]:
a[1,3]

13

In [ ]:
a[1,3]=14

In [ ]:
a

array([[ 0,  1,  2,  3],
       [10, 11, 12, 14]])

In [ ]:
a[1]

array([10, 11, 12, 14])

Slicing 

var[lower:upper:step]

In [ ]:
#-5 -4 -3 -2 -1
#0   1  2  3  4

a=np.array([10,11,12,13,14])

#we looking two element in array 11, 12

a[1:3]

array([11, 12])

In [ ]:
a[1:-2]

array([11, 12])

In [ ]:
a[-4:3]

array([11, 12])

Without Indices

In [ ]:
#omitted boundaries are assumed start or end
a[:3]

array([10, 11, 12])

In [ ]:
a[1:]

array([11, 12, 13, 14])

In [ ]:
a[::2]

array([10, 12, 14])

Slice are Refrences 

In [ ]:
a=np.array([0,1,2,3,4])

In [ ]:
#slicing
a[-2:]

array([3, 4])

In [ ]:
#insterting two value
a[-2:]=[-1,-2]

In [ ]:
a

array([ 0,  1,  2, -1, -2])

In [ ]:
#putting scalar value
a[-2:]=78

#sliced array share data

In [ ]:
a=np.array([0,1,2,3,4])

In [ ]:
#create new array
b=a[2:4]
b[0]=10

In [ ]:
b

array([10,  3])

In [ ]:
a

array([ 0,  1, 10,  3,  4])

In [ ]:
# array indexing based on boolean and other method

a=np.arange(0,80,10)
a

array([ 0, 10, 20, 30, 40, 50, 60, 70])

In [ ]:
indices=[1,2,-3]

In [ ]:
y=a[indices]

In [ ]:
y

array([10, 20, 50])

In [ ]:
a[indices]=78
a

array([ 0, 78, 78, 30, 40, 78, 60, 70])

In [ ]:
#indexing with Boolean
#or manual creation of mask
mask=np.array([0,1,1,0,0,1,0,0],dtype=bool)
y=a[mask]

In [ ]:
y

array([78, 78, 78])

#numpy function

#aarange()
#linespace
#array
#zeros
#ones


In [ ]:
#aarange (start,stop,step,dtype="")

np.arange(4)

array([0, 1, 2, 3])

In [ ]:
np.arange(0,2*np.pi,np.pi/4)

array([0.        , 0.78539816, 1.57079633, 2.35619449, 3.14159265,
       3.92699082, 4.71238898, 5.49778714])

In [ ]:
#careful
np.arange(1.5,2.1,0.3)

array([1.5, 1.8, 2.1])

In [ ]:
#ones zeros
#ones(shape,dtype='')
#zeros(shape,dtype='')
#if dtype is not specified default is 'float64'

np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((2,3),dtype='float32')

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [ ]:
np.zeros(3)

array([0., 0., 0.])

In [ ]:
#identity create n by n identity 
#deault data type 'float64'
a=np.identity(4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
#empty and Fill

#empty(shape,dtype='float64',order='c')
np.empty(2)

array([5.43230922e-312, 7.29112202e-304])

In [ ]:
a=np.full(2,5.0)

In [ ]:
a

array([5., 5.])

In [ ]:
a=np.empty(2)
a.fill(4)

In [ ]:
a

array([4., 4.])

In [ ]:
a[:]=3

In [ ]:
a

array([3., 3.])

In [ ]:
# Generate N evenly spaced
# elements between (and including) 
# start and stop values.
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:

# Generate N evenly spaced
# elements on a log scale
# between base**start and
# base**stop (default base=10)

np.logspace(0,1,5)

array([ 1.        ,  1.77827941,  3.16227766,  5.62341325, 10.        ])


  # Computation with Array
                                            

In [ ]:
#sum Method act on data storews in the array

a=np.array([[1,2,3],
            [4,5,6]])

In [ ]:

a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
#.sum defaults to adding up all the
#values in an aaray
a.sum()

21

In [ ]:
#supply the key word axis to
#sum along the diffrent axis

a.sum(axis=0)

array([5, 7, 9])

In [ ]:
a.sum(axis=-1)

array([ 6, 15])

In [ ]:
#Min/Max
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.min(a)

1

In [ ]:
a.min()

1

In [ ]:
a.min(axis=0)

array([1, 2, 3])

In [ ]:
a.max()

6

In [ ]:
a.max(axis=1)

array([3, 6])

In [ ]:
#Gives location of maximum value
a.argmax()

5

In [ ]:
np.argmin(a)

0

In [ ]:
#where
a=np.arange(-2,2)**2
a

array([4, 1, 0, 1])

In [ ]:
mask = a%2 ==0
mask

array([ True, False,  True, False])

In [ ]:
np.where(mask)

(array([0, 2]),)

In [ ]:
a= np.array([[1,2,3],
             [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a.mean()

3.5

In [ ]:
np.mean(a,axis=0)

array([2.5, 3.5, 4.5])

In [ ]:
#standard Deviation
a.std(axis=0)


array([1.5, 1.5, 1.5])

In [ ]:
#variance
np.var(a,axis=0)

array([2.25, 2.25, 2.25])

In [ ]:
#Array Broadcasting 
a=np.ones((3,5))
b=np.ones((5,))
b.reshape(1,5)
b[np.newaxis,:]

array([[1., 1., 1., 1., 1.]])

In [ ]:
c=a+b
c #shape==(3,5)
#logically
#temp_b=b.reshape(1,5)
#etem_b_repeat=temp_b.repeate(3,axis=0)

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

# Array brodcasting latex

In [ ]:
a=np.array([0,10,20,30])
b=np.array([0,1,2])

In [ ]:
y=a[:,np.newaxis]+b
y

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [ ]:
#op.reduce
#apply operator to all elements of array

a= np.array([1,2,3,4])
np.add.reduce(a)

10

In [ ]:
#for string

a= np.array(['ab','cd','ef'],dtype='object')
np.add.reduce(a)

'abcdef'

In [ ]:
a=np.array([1,0,0,1])
np.logical_and.reduce(a)

False

In [ ]:
np.logical_or.reduce(a)

True

In [ ]:
#for multi dimensional array
a=np.arange(3)+np.arange(0,40,10).reshape(-1,1)
a

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [ ]:
np.add.reduce(a,1)#row wise

array([ 3, 33, 63, 93])

In [ ]:
np.add.reduce(a) #colum wise

array([60, 64, 68])

In [ ]:
a=np.array([1,2,3,4])
np.add.accumulate(a)

array([ 1,  3,  6, 10])