<a href="https://colab.research.google.com/github/subodhkhanger/ml_series/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


$$arr= \begin{bmatrix}
  1 & 2 & 3 \\
  4 & 5 & 6
\end{bmatrix} $$

$$\begin{bmatrix}
  \begin{bmatrix}
    1 & 2 \\
    3 & 4
  \end{bmatrix}
  &
  \begin{bmatrix}
    5 & 6 \\
    7 & 8
  \end{bmatrix}
  \\
  \begin{bmatrix}
    9 & 10 \\
    11 & 12
  \end{bmatrix}
  &
  \begin{bmatrix}
    13 & 14 \\
    15 & 16
  \end{bmatrix}
\end{bmatrix}$$

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
type(arr)

numpy.ndarray

In [ ]:
arr.ndim

2


 $$\mathbf{a} + \mathbf{b}= \begin{bmatrix} 1 \\ 2 \\ 3 \end{bmatrix} + \begin{bmatrix} 4 \\ 5 \\ 6 \end{bmatrix} = \begin{bmatrix} 5 \\ 7 \\ 9 \end{bmatrix}$$


In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Element-wise addition
c = a + b
print(c)  # Output: [5 7 9]

# Element-wise subtraction
c = a - b
print(c)  # Output: [-3 -3 -3]

# Element-wise multiplication
c = a * b
print(c)  # Output: [ 4 10 18]

# Element-wise division
c = a / b
print(c)  # Output: [0.25 0.4  0.5 ]

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

# Dot product
c = np.dot(a, b)
print(c)

[[19 22]
 [43 50]]


In [ ]:
a = np.array([[1, 2], [3, 4]])

# Transpose
b = np.transpose(a)
print(b)

[[1 3]
 [2 4]]


In [ ]:
a = np.array([1, 2, 3])
print(a.shape) # Output: (3,)
b = a[np.newaxis, :]
print(b.shape) # Output: (1, 3)
c = a[:, np.newaxis]
print(c.shape) # Output: (3, 1)

(3,)
(1, 3)
(3, 1)


In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])
c = a + b
print(c) # Output: [11 22 33 44]

[11 22 33 44]


In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([10, 20])
c = a * b[:, np.newaxis]
print(c) # Output: [[10 20]
          #          [60 80]]

[[10 20]
 [60 80]]


In [ ]:
a = np.array([1, 2, 3, 4, 5])

# Sum
s = np.sum(a)
print(s) 
# Output: 15

# Mean
m = np.mean(a)
print(m)  
# Output: 3.0

# Minimum
mi = np.min(a)
print(mi)  
# Output: 1

# Maximum
ma = np.max(a)
print(ma)  

# Output: 5

# Standard deviation
std = np.std(a)
print(std)  
# Output: 1.41421356

15
3.0
1
5
1.4142135623730951


In [ ]:
arr = np.arange(0, 10, 2)
print(arr)

[0 2 4 6 8]


In [ ]:
arr = np.linspace(0, 1, 5)
print(arr)

[0.   0.25 0.5  0.75 1.  ]


In [ ]:
arr = np.zeros((3, 4))
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
arr = np.ones((2, 3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
arr = np.zeros((3, 3))
arr.fill(5)
print(arr)

[[5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]]


In [ ]:
emp = np.empty((2, 3))
print(emp)

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
arr = np.array([1, 2, 3, 4, 5])

# Access the third element
elem = arr[2]
print(elem)  # Output: 3

# Access elements using boolean indexing
mask = arr > 3
subset = arr[mask]
print(subset)  # Output: [4 5]

# Access elements using fancy indexing
indices = [0, 2, 4]
subset = arr[indices]
print(subset)  # Output: [1 3 5]

3
[4 5]
[1 3 5]


In [ ]:
arr = np.array([1, 2, 3, 4, 5])
elem = arr[2]
print(elem)  # Output: 3

3


In [ ]:
arr = np.array([1, 2, 3, 4, 5])
subset = arr[1:4]
print(subset)  # Output: [2 3 4]

[2 3 4]


In [ ]:
arr = np.array([1, 2, 3, 4, 5])
subset = arr[::2]
print(subset)  # Output: [1 3 5]

[1 3 5]


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
sub = arr[0:2, 1:3]
print(sub)  # Output: [[2 3]
            #          [5 6]]

[[2 3]
 [5 6]]


In [ ]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
sub = arr[..., 0]
print(sub)  # Output: [[1 3]
            #          [5 7]]

[[1 3]
 [5 7]]


In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])
c = np.where(a > 2, b, a)
print(c) 
# Output: [ 1  2 30 40]

[ 1  2 30 40]


In [ ]:
a = np.array([1, 3, 2, 4, 5])
max_index = np.argmax(a)
print("The maximum value is:", a[max_index])
print("The index of the maximum value is:", max_index)

The maximum value is: 5
The index of the maximum value is: 4


In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
max_indices = np.argmax(a, axis=1)
print("The indices of the maximum values in each row are:", max_indices)

The indices of the maximum values in each row are: [2 2 2]


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

max_val = np.max(arr, axis=0)
min_val = np.min(arr, axis=1)
print(max_val)  # Output: [4 5 6]
print(min_val)  # Output: [1 4]

[4 5 6]
[1 4]


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
sum_val = np.sum(arr, axis=0)
print(sum_val)  # Output: [5 7 9]

[5 7 9]


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
prod_val = np.prod(arr, axis=1)
print(prod_val)  # Output: [ 6 120]

[  6 120]


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
mean_val = np.mean(arr, axis=0)
print(mean_val)  # Output: [2.5 3.5 4.5]

[2.5 3.5 4.5]


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
std_val = np.std(arr, axis=1)
print(std_val)  # Output: [0.81649658 0.81649658]

[0.81649658 0.81649658]


In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.add.reduce(a, axis=0)
print(b) # Output: [4 6]

[4 6]


In [ ]:
a = np.array([[True, False], [True, True]])
b = np.logical_and.reduce(a, axis=1)
print(b) # Output: [False  True]

[False  True]


In [ ]:
a = np.array([1, 2, 3, 4])
b = np.add.accumulate(a)
print(b) # Output: [ 1  3  6 10]

[ 1  3  6 10]


In [ ]:
a = np.array([[True, False], [False, False]])
b = np.logical_or.reduce(a, axis=0)
print(b) # Output: [ True False]

[ True False]
